find_package(MySQL REQUIRED)
find_package(ROOT 6.06.02 REQUIRED)
find_package(CURL REQUIRED)
find_package(ZeroMQ REQUIRED)

o2_define_bucket(
  NAME
  o2_tobejct2json

  DEPENDENCIES
  ${ROOT_LIBRARIES}
  ${CURL_LIBRARIES}
  ${ZeroMQ_LIBRARY_STATIC}

  SYSTEMINCLUDE_DIRECTORIES
  ${ROOT_INCLUDE_DIR}
  ${MYSQL_INCLUDE_DIRS}
  ${CURL_INCLUDE_DIRS}
  ZeroMQ_INCLUDE_DIR
)
